### ISSUE TITLE
The implementation example appeared the following error 

### ISSUE THREAD

**Issue by ym1623** [EusthEnoptEron/node-svgchart#1]
[ERROR] Error
Error: write EPIPE
    at errnoException (net.js:781:11)
    at Object.afterWrite (net.js:594:19)

**Comment by EusthEnoptEron** [comment]
Could you specify which version of node.js you are using and which example you were trying to run?

**Comment by ym1623** [comment]
I am using NVM management node, the node v. 0.8.0 and node v. 0.6.2.1, when I run the example next all the examples will appear these mistakes, I doubt is node - svgchart. In js spawn = require (' child_process '). This a connection spawn the problems

**Comment by ym1623** [comment]
Excuse me, the problem can be repaired?

**Comment by EusthEnoptEron** [comment]
Sorry for the delay! I think I might have found the error: Do you have the "convert" command on your machine? It's required to convert SVG -> PNG. (Should come with ImageMagick IIRC)

**Comment by ym1623** [comment]
thx~ It has to work properly
