### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by joe-bowman** [EusthEnoptEron/node-svgchart#3]
Hey,

Thanks for a useful bit of code. I've submitted a pull request to fix an issue with apostrophe in labels.

Could you add a licence to the repo so I can use the code in another project; ideally NOT GPL as it is too restrictive for my needs.

Thank you :+1:

**Comment by EusthEnoptEron** [comment]
Howdy,

Great that it proved useful to you, and thanks for the PR. I'll look into it later.

Regarding the license, would MIT work for you?

Finally, just fyi, if you're looking to render charts, phantomjs might be a better choice depending on your needs, since it is powered by webkit and therefore less hacky. In fact, we succeeded in setting it up at work in a 
reasonable amount of time and it's even a bit faster.

**Comment by joe-bowman** [comment]
Hey,

MIT licence is perfect, thank you.

Thanks for the heads up about PhantomJS. I looked into this originally 
(although using Xvfb and trying to hack Flash-based anycharts into it 
(as there is plenty of anecdotal evidence it _can_ be done, just not 
much information!). Needless to say it didn't go well :) As speed is 
quite important in this case, it is something I may revisit.

Thank you.

Regards,

Joe

On 06/09/13 16:54, EusthEnoptEron wrote:

> Howdy,
> 
> Great that it proved useful to you, and thanks for the PR. I'll look 
> into it later.
> 
> Regarding the license, would MIT work for you?
> 
> Finally, just fyi, if you're looking to render charts, phantomjs might 
> be a better choice depending on your needs, since it is powered by 
> webkit and therefore less hacky. In fact, we succeeded in setting it 
> up at work in a
> reasonable amount of time and it's even a bit faster.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/EusthEnoptEron/node-svgchart/issues/3#issuecomment-23950004.

## 

Joe Bowman B.Sc (Hons), M.Sc
Quality Assurance
eDigitalResearch,
Vanbrugh House,
Grange Drive
Hedge End
Hampshire
SO30 2AF
www.edigitalresearch.com http://www.edigitalresearch.com
Switchboard: +44 (0) 1489 772920
Direct Dial: +44 (0) 1489 775193
Fax: +44 (0) 1489 772922

One third of smartphone owners are making a purchase on a weekly basis. 
Download your copy of the Role of Mobile in Retail Commerce to find out more.
https://ecustomeropinions.com/survey/survey.php?sid=185148865

We are delighted to be one of the top 100 The Sunday Times Best Small
Companies to Work For 2013. 

This message is sent in confidence for the addressee only. The contents are
not to be disclosed to anyone other than the addressee. Unauthorised
recipients must preserve this confidentiality and should please advise the
sender immediately of any error in transmission.

Any attachment(s) to this message have been checked for viruses, but please
rely on your own virus checker and procedures.

Please note that Internet email is not a secure communications medium. We
advise that you understand and observe this when emailing us.

eDigitalResearch plc is a public limited company registered at the Registrar
Of Companies for England and Wales. Company registration number: 5424597

Registered Office: Vanbrugh House, Hedge End, Hampshire, SO30 2AF
PS: Save paper - do you really need to print this email?

**Comment by EusthEnoptEron** [comment]
> I looked into this originally
> (although using Xvfb and trying to hack Flash-based anycharts into it
> (as there is plenty of anecdotal evidence it _can_ be done, just not
> much information!). Needless to say it didn't go well :) As speed is
> quite important in this case, it is something I may revisit.

I see, I made similar experiences in that field... ;)

If you want to give the PhantomJS solution a whirl, check out this gist to get you started:
https://gist.github.com/EusthEnoptEron/6467544

```
git clone https://gist.github.com/6467544.git
cd 6467544
sh install.sh
./phantomjs index.js
```
